name: list_page
version: 1.0.0+1
packages:
  - packages/**
  - ./

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

    # Shared
    environment:
      sdk: 3.5.4
      flutter: 3.24.4

    dependencies:
      flutter_riverpod: 2.6.1
      freezed_annotation: 2.4.4
      riverpod_annotation: 2.6.1
      dio: 5.7.0
      firebase_crashlytics: 4.1.5
      intl: 0.19.0
      retrofit: 4.4.1
    
    dev_dependencies:
      build_runner: 2.4.13
      import_sorter: 4.6.0
      import_path_converter: 1.0.1
      freezed: 2.5.7
      logger: 2.5.0
      riverpod_generator: 2.6.3
      flutter_lints: 5.0.0
      

    hooks:
      post: fvm dart pub run build_runner build --delete-conflicting-outputs

scripts:
  analyze: melos exec -- fvm flutter analyze
  format: melos exec -- fvm dart format .
  getpub: melos exec -- fvm flutter pub get
  cleanbuild: 
    run: melos exec -- fvm flutter clean
    packageFilters:
      flutter: true
    description: run on the clean on packages
  watch:
    run: melos exec --  fvm dart run build_runner watch -d
    packageFilters:
      flutter: true
    description: run on the build_runner package and watch
  br: 
    run: melos exec -- fvm flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      flutter: true
    description: run on the build_runner package
  
  postclean:
    run: melos run clean:fvm flutter --no-select
    description: Runs "flutter clean" in all Flutter packages

  precommit:
    run: |
      melos exec -- fvm flutter pub get
      melos exec -- fvm dart analyze --no-fatal-warnings
      melos exec -- fvm dart fix --apply
      melos exec -- fvm flutter pub run build_runner build --delete-conflicting-outputs
      melos exec -- fvm flutter pub run import_sorter:main lib\/*
      melos exec -- fvm flutter pub run import_path_converter:main lib\/*
      melos exec -- fvm dart format .
      melos exec -- fvm flutter pub get
    packageFilters:
      flutter: true
    description: Build all example apps

  locali:
    run: melos exec -- fvm flutter gen-l10n
    packageFilters:
      flutter: true
    description: run on the localization package

